Repository tower-defense-L2/projet-L2, pull requests merged in 2023-03, with the labels that each got.

#29 merge(fix/doc): reformatage des commentaire
  doc/html/bc_s.png
  doc/html/bdwn.png
  doc/html/closed.png
  doc/html/doc.png
  doc/html/doxygen.css
  doc/html/doxygen.svg
  doc/html/dynsections.js
  doc/html/folderclosed.png
  doc/html/folderopen.png
  doc/html/graph_legend.html
  doc/html/graph_legend.md5
  doc/html/graph_legend.png
  doc/html/index.html
  doc/html/jquery.js
  doc/html/md__r_e_a_d_m_e.html
  doc/html/menu.js
  doc/html/menudata.js
  doc/html/nav_f.png
  doc/html/nav_g.png
  doc/html/nav_h.png
  doc/html/open.png
  doc/html/pages.html
  doc/html/search/all_0.html
  doc/html/search/all_0.js
  doc/html/search/close.svg
  doc/html/search/mag_sel.svg
  doc/html/search/nomatches.html
  doc/html/search/pages_0.html
  doc/html/search/pages_0.js
  doc/html/search/search.css
  doc/html/search/search.js
  doc/html/search/search_l.png
  doc/html/search/search_m.png
  doc/html/search/search_r.png
  doc/html/search/searchdata.js
  doc/html/splitbar.png
  doc/html/sync_off.png
  doc/html/sync_on.png
  doc/html/tab_a.png
  doc/html/tab_b.png
  doc/html/tab_h.png
  doc/html/tab_s.png
  doc/html/tabs.css
  doc/latex/Makefile
  doc/latex/doxygen.sty
  doc/latex/longtable_doxygen.sty
  doc/latex/md__r_e_a_d_m_e.tex
  doc/latex/refman.tex
  doc/latex/tabu_doxygen.sty
  include/init_supr_sdl.h
  include/interaction_souris.h
  include/struct_sdl.h
  src/jeux.c
  src/menu.c
  src/sdl/init_supr_sdl.c
  src/sdl/interaction_souris.c
Labels: bug, documentation

#30 merge(fix/make): ajout du standard c11 et macro
  Makefile
  README.md
Labels: documentation, important

#33 merge(style/github): ajout au readme
  Makefile
  README.md
Labels: documentation

#45 merge(fix/docs): gestion static/extern
  doc/Doxyfile
  include/mouvement_ennemi.h
  include/placement_tours.h
  include/possibilite_tours.h
  src/jeux.c
  src/mouvement_ennemi.c
  src/placement_tours.c
  src/possibilite_tours.c
  src/sdl/init_supr_sdl.c
  src/sdl/interaction_souris.c
Labels: documentation

#46 merge(style/github): ajout de la doc readme
  README.md
Labels: documentation

#52 merge(logic/a-star): implementation de la logique map
  include/file.h
  include/map.h
  include/struct.h
  src/file.c
  src/map.c
Labels: enhancement, important
